### PR TITLE
Add tx_id to bound logger

### PR DESCRIPTION
**Pull request by iwootten**
**Changes**

Add tx_id to log messages if within decrypted payload.

**How to test**

Use within sdx-compose setup and check that log messages include tx_id.

**Who can test**

Anyone but @iwootten

### CODE REVIEW

**Comment by ajmaddaford** [comment]
I think we need to look at the logging done by the async_consumer. The log line for acknowledging the message - `2016-07-20 16:05:17,988|INFO: sdx-collect: d_tag=1 event='Acknowledging message'` - doesn't have any context e.g. the tx_id.

**Comment by iwootten** [comment]
As I said offline, it appears that the get_receipt_endpoint is throwing some errors in tests causing them to be output in the logs. Should this method be properly mocked to avoid the errors?

**Comment by ajmaddaford** [comment]
Looks like the errors are valid for the tests that are being run, for example:
In the `test_receipt_endpoint_invalid_json` test the error `sdx-collect: exception="KeyError('metadata',)" event='Unable to get required data from json'` is generated when testing the `get_receipt_endpoint method` with invalid json. Not sure what help mocking would be?

**Comment by ajmaddaford** [comment]
Maybe it's better to turn off logging in tests?

**Comment by iwootten** [comment]
If it's expected behaviour I think it's fine, just a little unclear I guess.

**Comment by ajmaddaford** [comment]
Yeah, I think generally logging clutters up tests so maybe we should think about disabling logging in tests.

**Comment by ajmaddaford** [comment]
👍

**Pull request merged**
